services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./src:/usr/share/nginx/html/src
      - ./public:/usr/share/nginx/html/public
