replicaCount: 1

image:
  repository: ghcr.io/noi-techpark/opendatahub-analytics-v2/analytics
  pullPolicy: IfNotPresent
  tag: sometag

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true

  className: nginx
  hosts:
    - host: v2-beta.analytics.opendatahub.testingmachine.eu
      paths: 
        - path: "/"
          pathType: Prefix


