replicaCount: 1

image:
  repository: ghcr.io/noi-techpark/opendatahub-analytics-v2/analytics
  pullPolicy: IfNotPresent
  tag: sometag

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true

  annotations:
    cert-manager.io/issuer: "letsencrypt-prod"

  className: nginx
  tls:
    - hosts:
      - v2-beta.analytics.opendatahub.testingmachine.eu
      secretName: tls-analytics-v2
  hosts:
    - host: v2-beta.analytics.opendatahub.testingmachine.eu
      paths: 
        - path: "/"
          pathType: Prefix


